-- =============================================================================
-- SStore Product Service — consolidated schema (v2)
-- =============================================================================
-- Source of truth for the product catalog. Owned by product-service.
-- -----------------------------------------------------------------------------
-- Conventions:
--   * `id` is a uuid generated by pgcrypto's gen_random_uuid().
--   * Money is stored as bigint in the smallest currency unit (paise for INR,
--     cents for USD, etc.). Never use numeric/float for money.
--   * All timestamps are timestamptz in UTC.
--   * Soft delete via `deleted_at` (NULL = active). Hard delete is reserved
--     for GDPR-style erasure and admin tooling.
--   * Slugs are URL-safe identifiers generated from the product name; they are
--     unique so the storefront can use `/p/<slug>` style URLs.
--   * `version` columns back JPA optimistic locking where present.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------------
-- updated_at trigger function
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Products (catalog master)
-- Categories / brand / tags / dimensions were removed in this consolidation:
-- the storefront is a flat catalog with admin filtering by status / stock /
-- featured. If we ever reintroduce a real taxonomy (or shipping dimensions
-- etc.) we can add it back in a V2 migration without disturbing existing rows.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    sku                 text NOT NULL UNIQUE,
    slug                text NOT NULL UNIQUE,
    name                text NOT NULL,
    description         text,
    price               bigint NOT NULL CHECK (price >= 0),
    currency            text NOT NULL DEFAULT 'INR' CHECK (length(currency) = 3),

    -- Catalog visibility is governed solely by `active` + `deleted_at`.
    -- There's no separate "draft" state — admin fills in price/description/
    -- stock on the edit page before flipping `active` to true.
    taxable             boolean NOT NULL DEFAULT true,

    image               text,                       -- primary image URL (denormalised)
    avg_rating          numeric(3,2) NOT NULL DEFAULT 0 CHECK (avg_rating >= 0 AND avg_rating <= 5),
    review_count        integer NOT NULL DEFAULT 0 CHECK (review_count >= 0),
    sold_count          integer NOT NULL DEFAULT 0 CHECK (sold_count >= 0),

    stock               integer NOT NULL DEFAULT 0 CHECK (stock >= 0),

    active              boolean NOT NULL DEFAULT true,
    featured            boolean NOT NULL DEFAULT false,

    version             bigint NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz,
    published_at        timestamptz                  -- first time status moved to ACTIVE
);

CREATE INDEX IF NOT EXISTS idx_products_active      ON products(active)      WHERE active = true  AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_featured    ON products(featured)    WHERE featured = true AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_created     ON products(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_updated     ON products(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_sku         ON products(sku)         WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_slug        ON products(slug)        WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_products_name_trgm   ON products USING gin (name gin_trgm_ops);
-- Low-stock index — hardcoded threshold at 5 units (products.low_stock_threshold was dropped).
CREATE INDEX IF NOT EXISTS idx_products_low_stock   ON products(stock)
    WHERE active = true AND deleted_at IS NULL AND stock <= 5;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Maintain published_at: set the first time the product is marked active.
CREATE OR REPLACE FUNCTION set_published_at() RETURNS trigger AS $$
BEGIN
    IF NEW.active = true AND (OLD.active IS NULL OR OLD.active = false) THEN
        NEW.published_at := COALESCE(NEW.published_at, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_published_at ON products;
CREATE TRIGGER trg_products_published_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_published_at();

-- ---------------------------------------------------------------------------
-- Event outbox (transactional outbox pattern; shared shape across services)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_outbox (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type  text NOT NULL,
    aggregate_id    text NOT NULL,
    event_type      text NOT NULL,
    topic           text NOT NULL,
    payload         jsonb NOT NULL,
    headers         jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    published_at    timestamptz
);

CREATE INDEX IF NOT EXISTS idx_event_outbox_pending
    ON event_outbox(created_at)
    WHERE published_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_event_outbox_aggregate
    ON event_outbox(aggregate_type, aggregate_id);
