apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SERVER_PORT: "8082"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/product_db"
  SPRING_DATASOURCE_USERNAME: "admin"

  JPA_DDL_AUTO: "validate"
  JPA_SHOW_SQL: "false"

  SPRING_APPLICATION_NAME: "product-service"

  KEYCLOAK_ISSUER_URI: "https://auth.sstore.local/realms/sstore"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/sstore/protocol/openid-connect/certs"

  FLYWAY_ENABLED: "true"