apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - secret.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: postgres-init-script
    files:
      - init-dbs.sql