apiVersion: v1
kind: ConfigMap

metadata:
  name: api-gateway-config

data:
  SERVER_PORT: "9090"

  PRODUCT_SERVICE_URL: "http://product-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"

  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "sstore"

  KEYCLOAK_ISSUER_URI: "https://auth.sstore.local/realms/sstore"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/sstore/protocol/openid-connect/certs"