apiVersion: v1
kind: Secret

metadata:
  name: keycloak-secret

type: Opaque

stringData:
  KC_DB_USERNAME: admin
  KC_DB_PASSWORD: admin

  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin